# EDA

In [1]:
import numpy as np
import pandas as pd
#import pickle
from IPython.display import display
from functions import get_current_weekday, calculate_nfl_week, get_next_sunday, get_current_year

In [2]:
day = get_current_weekday()

In [3]:
date_string = get_next_sunday(day)

In [4]:
week = calculate_nfl_week(date_string)

In [5]:
season = get_current_year()

In [6]:
pd.set_option('display.max_rows', None)

In [7]:
fd_def_df = pd.read_csv('FD_def_for_model_' + str(season) + '_' + str(week) + '.csv')
dk_def_df = pd.read_csv('DK_def_for_model_' + str(season) + '_' + str(week) + '.csv')

In [8]:
fd_def_df.head()

,position,salary,team,opponent,date,week,season,spread_line,home_team,outdoors,grass,total_line,opp_total,opp_vs_def_L8,opp_vs_def_L8_lin,opp_vs_def_L8_exp
0,D,5000,SF,ARI,10-06-2024,5,2024,7.5,1,1,1,49.5,21.00,5.000,4.87,5.145
1,D,4800,SEA,NYG,10-06-2024,5,2024,7.0,1,1,0,42.5,17.75,8.250,7.50,6.610
2,D,4700,GB,LAR,10-06-2024,5,2024,3.0,0,0,0,48.5,22.75,6.125,6.56,6.400
3,D,4600,CHI,CAR,10-06-2024,5,2024,3.5,1,1,1,40.5,18.50,8.500,6.90,5.290
4,D,4500,BAL,CIN,10-06-2024,5,2024,2.5,0,1,0,48.5,23.00,6.875,5.32,4.340

In [9]:
dk_def_df.head()

,position,salary,team,opponent,date,week,season,spread_line,home_team,outdoors,grass,total_line,opp_total,opp_vs_def_L8,opp_vs_def_L8_lin,opp_vs_def_L8_exp
0,D,3700,SF,ARI,10-06-2024,5,2024,7.0,1,1,1,48.5,20.75,5.000,4.87,5.145
1,D,3600,CHI,CAR,10-06-2024,5,2024,4.0,1,1,1,41.0,18.50,8.500,6.90,5.290
2,D,3500,SEA,NYG,10-06-2024,5,2024,7.0,1,1,0,42.5,17.75,8.250,7.50,6.610
3,D,3300,MIA,NE,10-06-2024,5,2024,1.0,0,1,0,35.5,17.25,11.625,14.40,14.970
4,D,3200,LV,DEN,10-06-2024,5,2024,-2.5,0,1,1,35.5,19.00,7.625,7.24,6.580

In [10]:
fd_def_df = fd_def_df.drop(columns = ['date'])
dk_def_df = dk_def_df.drop(columns = ['date'])

In [11]:
fd_def_df['name'] = fd_def_df['team']
dk_def_df['name'] = dk_def_df['team']

In [12]:
fd_def_df['status'] = 'Active'
dk_def_df['status'] = 'Active'

In [13]:
fd_def_df.describe().T

,count,mean,std,min,25%,50%,75%,max
salary,22.0,3959.090909,572.096471,3000.00,3525.00000,3950.0000,4375.00000,5000.000
week,22.0,5.000000,0.000000,5.00,5.00000,5.0000,5.00000,5.000
season,22.0,2024.000000,0.000000,2024.00,2024.00000,2024.0000,2024.00000,2024.000
spread_line,22.0,0.000000,3.997023,-7.50,-2.87500,0.0000,2.87500,7.500
home_team,22.0,0.500000,0.511766,0.00,0.00000,0.5000,1.00000,1.000
outdoors,22.0,0.818182,0.394771,0.00,1.00000,1.0000,1.00000,1.000
grass,22.0,0.545455,0.509647,0.00,0.00000,1.0000,1.00000,1.000
total_line,22.0,43.681818,4.816997,35.50,41.00000,43.5000,48.25000,49.500
opp_total,22.0,21.840909,3.129683,16.50,19.31250,22.3750,24.00000,28.500
opp_vs_def_L8,22.0,6.528409,2.265467,2.75,4.90625,5.7500,7.90625,11.625
opp_vs_def_L8_lin,22.0,6.718182,2.832217,2.72,5.06250,6.2600,7.55250,14.400
opp_vs_def_L8_exp,22.0,6.313182,2.970738,1.62,4.57125,5.9525,6.94375,14.970

In [14]:
dk_def_df.describe().T

,count,mean,std,min,25%,50%,75%,max
salary,20.0,2900.00000,403.928081,2300.00,2600.00000,2850.0000,3125.00000,3700.000
week,20.0,5.00000,0.000000,5.00,5.00000,5.0000,5.00000,5.000
season,20.0,2024.00000,0.000000,2024.00,2024.00000,2024.0000,2024.00000,2024.000
spread_line,20.0,0.00000,4.045791,-7.00,-3.00000,0.0000,3.00000,7.000
home_team,20.0,0.50000,0.512989,0.00,0.00000,0.5000,1.00000,1.000
outdoors,20.0,0.80000,0.410391,0.00,1.00000,1.0000,1.00000,1.000
grass,20.0,0.50000,0.512989,0.00,0.00000,0.5000,1.00000,1.000
total_line,20.0,43.65000,4.936705,35.50,41.00000,44.5000,48.50000,49.000
opp_total,20.0,21.82500,3.191374,16.50,18.87500,22.7500,24.06250,27.750
opp_vs_def_L8,20.0,6.68750,2.315032,2.75,4.96875,6.1250,8.06250,11.625
opp_vs_def_L8_lin,20.0,6.83750,2.945365,2.72,5.08750,6.5300,7.66250,14.400
opp_vs_def_L8_exp,20.0,6.41925,3.093014,1.62,4.64375,6.1575,7.14375,14.970

In [15]:
fd_qb_df = pd.read_csv('FD_qb_for_model_' + str(season) + '_' + str(week) + '.csv')
dk_qb_df = pd.read_csv('DK_qb_for_model_' + str(season) + '_' + str(week) + '.csv')

In [16]:
fd_qb_df.head()

,name,team,position,salary,opponent,status,season,week,FD_Pts_DvP,DK_Pts_DvP,...,int_pct,wind,div_game,spread_line,total_line,outdoors,grass,home_team,pred_total,opp_total
0,Josh Allen,BUF,QB,9300,HOU,Active,2024,5,17.5625,18.4375,...,0.012605,0,0,-1.5,47.5,0,0,0,23.00,24.50
1,Lamar Jackson,BAL,QB,8800,CIN,Active,2024,5,16.8500,17.3500,...,0.008969,12,1,2.5,48.5,1,0,0,25.50,23.00
2,Jayden Daniels,WAS,QB,8700,CLE,Active,2024,5,15.4900,15.4900,...,0.009434,5,0,3.0,43.5,1,1,1,23.25,20.25
3,CJ Stroud,HOU,QB,8400,BUF,Active,2024,5,15.0250,15.4000,...,0.007968,0,0,1.5,47.5,0,0,1,24.50,23.00
4,Jordan Love,GB,QB,8200,LAR,Active,2024,5,19.2175,20.3425,...,0.021818,0,0,3.0,48.5,0,0,0,25.75,22.75

In [17]:
dk_qb_df.head()

,name,team,position,salary,opponent,status,season,week,FD_Pts_DvP,DK_Pts_DvP,...,int_pct,wind,div_game,spread_line,total_line,outdoors,grass,home_team,pred_total,opp_total
0,Josh Allen,BUF,QB,7700,HOU,Active,2024,5,17.5625,18.4375,...,0.012605,0,0,-1.0,47.0,0,0,0,23.00,24.00
1,Lamar Jackson,BAL,QB,7500,CIN,Active,2024,5,16.8500,17.3500,...,0.008969,12,1,2.5,48.5,1,0,0,25.50,23.00
2,CJ Stroud,HOU,QB,7200,BUF,Active,2024,5,15.0250,15.4000,...,0.007968,0,0,1.0,47.0,0,0,1,24.00,23.00
3,Jayden Daniels,WAS,QB,6800,CLE,Active,2024,5,15.4900,15.4900,...,0.009434,5,0,3.0,43.5,1,1,1,23.25,20.25
4,Kyler Murray,ARI,QB,6700,SF,Active,2024,5,17.8150,18.3150,...,0.016260,6,1,-7.0,48.5,1,1,0,20.75,27.75

In [18]:
fd_qb_df.describe().T

,count,mean,std,min,25%,50%,75%,max
salary,84.0,6407.142857,769.569699,6000.000000,6000.000000,6000.000000,6600.000000,9300.000000
season,84.0,2024.000000,0.000000,2024.000000,2024.000000,2024.000000,2024.000000,2024.000000
week,84.0,5.000000,0.000000,5.000000,5.000000,5.000000,5.000000,5.000000
FD_Pts_DvP,84.0,17.005655,1.831123,14.090000,15.645000,16.818750,17.903750,21.340000
DK_Pts_DvP,84.0,17.641815,1.918039,14.902500,15.832500,17.350000,18.732500,21.590000
QB_role,84.0,1.750000,0.435613,1.000000,1.750000,2.000000,2.000000,2.000000
completions_L8,84.0,14.692334,6.749054,0.500000,9.687500,17.857375,19.125000,26.750000
attempts_L8,84.0,23.073825,10.088179,0.500000,16.843750,27.720470,29.468750,39.375000
passing_yards_L8,84.0,156.687661,75.028556,8.857143,92.237500,190.177930,194.860645,294.000000
passing_tds_L8,84.0,0.839175,0.577666,0.000000,0.250000,0.875000,1.139014,2.500000
interceptions_L8,84.0,0.598637,0.318514,0.000000,0.375000,0.624253,0.750000,1.500000
sacks_L8,84.0,1.849590,0.951348,0.000000,1.281250,2.011766,2.048899,4.500000
passing_air_yards_L8,84.0,177.329758,84.648036,5.000000,133.456250,215.348113,220.656250,351.250000
pacr_L8,84.0,1.093409,0.666930,0.446049,0.841712,0.961580,1.060254,5.000000
carries_L8,84.0,3.330071,1.970111,0.000000,2.000000,3.500000,3.662746,11.500000
rushing_yards_L8,84.0,14.584866,12.565242,-2.500000,4.625000,16.100802,18.550000,67.750000
rushing_tds_L8,84.0,0.146131,0.204011,0.000000,0.000000,0.125000,0.183676,1.000000
comp_pct,84.0,0.640037,0.080635,0.448980,0.607499,0.644195,0.658279,1.000000
yds_per_attempt,84.0,7.060913,3.542830,2.750000,6.008629,7.029313,7.255171,37.000000
td_pct,84.0,0.032091,0.018574,0.000000,0.016651,0.040296,0.041089,0.072727
sack_pct,84.0,0.088705,0.058432,0.000000,0.066026,0.072998,0.099890,0.333333
int_pct,84.0,0.031071,0.034539,0.000000,0.017450,0.022520,0.034940,0.250000
wind,84.0,6.404762,5.013522,0.000000,4.000000,5.000000,10.000000,17.000000
div_game,84.0,0.440476,0.499426,0.000000,0.000000,0.000000,1.000000,1.000000
spread_line,84.0,0.369048,3.894790,-7.500000,-2.625000,1.500000,3.000000,7.500000
total_line,84.0,44.059524,4.576923,35.500000,42.500000,43.500000,48.500000,49.500000
outdoors,84.0,0.797619,0.404188,0.000000,1.000000,1.000000,1.000000,1.000000
grass,84.0,0.511905,0.502860,0.000000,0.000000,1.000000,1.000000,1.000000
home_team,84.0,0.500000,0.503003,0.000000,0.000000,0.500000,1.000000,1.000000
pred_total,84.0,22.214286,3.044386,16.500000,20.250000,23.000000,24.500000,28.500000
opp_total,84.0,21.845238,2.964881,16.500000,19.937500,22.375000,24.250000,28.500000

In [19]:
dk_qb_df.describe().T

,count,mean,std,min,25%,50%,75%,max
salary,62.0,4925.806452,977.272129,4000.000000,4000.000000,4800.000000,5400.000000,7700.000000
season,62.0,2024.000000,0.000000,2024.000000,2024.000000,2024.000000,2024.000000,2024.000000
week,62.0,5.000000,0.000000,5.000000,5.000000,5.000000,5.000000,5.000000
FD_Pts_DvP,62.0,16.998710,1.937957,14.090000,15.528750,16.818750,18.081250,21.340000
DK_Pts_DvP,62.0,17.613629,2.010872,14.902500,15.575625,17.506250,18.857500,21.590000
QB_role,62.0,1.677419,0.471280,1.000000,1.000000,2.000000,2.000000,2.000000
completions_L8,62.0,14.880644,6.817468,0.500000,9.312500,17.857375,19.750000,25.250000
attempts_L8,62.0,23.262518,10.184142,0.500000,16.281250,27.720470,30.531250,38.625000
passing_yards_L8,62.0,156.995550,76.603271,8.857143,87.912500,176.712500,201.531250,281.000000
passing_tds_L8,62.0,0.852203,0.568190,0.000000,0.446429,0.875000,1.139014,2.500000
interceptions_L8,62.0,0.591431,0.330010,0.000000,0.375000,0.624253,0.750000,1.500000
sacks_L8,62.0,1.908980,0.966399,0.000000,1.343750,1.937500,2.218750,4.500000
passing_air_yards_L8,62.0,178.451539,85.873833,5.000000,127.568750,213.375000,224.343750,351.250000
pacr_L8,62.0,1.047649,0.525463,0.446049,0.827532,0.961580,1.092235,4.500000
carries_L8,62.0,3.315497,2.019511,0.500000,2.000000,3.250000,4.000000,11.500000
rushing_yards_L8,62.0,15.145483,13.478164,-1.125000,4.541667,16.050401,19.625000,67.750000
rushing_tds_L8,62.0,0.147252,0.221245,0.000000,0.000000,0.000000,0.183676,1.000000
comp_pct,62.0,0.643276,0.085689,0.500000,0.606169,0.644195,0.660152,1.000000
yds_per_attempt,62.0,7.061163,4.048447,2.750000,5.848130,6.994425,7.322254,37.000000
td_pct,62.0,0.033121,0.018443,0.000000,0.021053,0.039117,0.041089,0.072727
sack_pct,62.0,0.096068,0.064333,0.000000,0.064663,0.072998,0.106532,0.333333
int_pct,62.0,0.029866,0.032909,0.000000,0.016404,0.022520,0.034102,0.250000
wind,62.0,6.177419,5.036015,0.000000,4.000000,5.000000,10.000000,17.000000
div_game,62.0,0.500000,0.504082,0.000000,0.000000,0.500000,1.000000,1.000000
spread_line,62.0,0.161290,4.027339,-7.000000,-3.000000,1.000000,3.000000,7.000000
total_line,62.0,43.725806,4.811766,35.500000,41.000000,44.500000,48.500000,49.000000
outdoors,62.0,0.806452,0.398304,0.000000,1.000000,1.000000,1.000000,1.000000
grass,62.0,0.516129,0.503819,0.000000,0.000000,1.000000,1.000000,1.000000
home_team,62.0,0.516129,0.503819,0.000000,0.000000,1.000000,1.000000,1.000000
pred_total,62.0,21.943548,3.179861,16.500000,19.000000,23.000000,24.187500,27.750000
opp_total,62.0,21.782258,3.094311,16.500000,19.000000,22.500000,24.000000,27.750000

In [20]:
fd_flex_df = pd.read_csv('FD_FLEX_for_model_' + str(season) + '_' + str(week) + '.csv')
dk_flex_df = pd.read_csv('DK_FLEX_for_model_' + str(season) + '_' + str(week) + '.csv')

In [21]:
fd_flex_df.head()

,name,team,position,salary,opponent,status,season,week,index,DK_Pts_RB_DvP,...,pos_WR,qb_comp,qb_att,qb_yds,qb_pass_td,qb_int,qb_comp_pct,qb_yds_per_att,qb_td_pct,qb_int_pct
0,CeeDee Lamb,DAL,WR,9400,PIT,Active,2024,5,0,16.4500,...,1,26.750,39.375,294.000,2.125,0.750,0.679365,7.466667,0.053968,0.019048
1,Ja'Marr Chase,CIN,WR,9300,BAL,Active,2024,5,1,21.8250,...,1,24.000,33.375,257.125,1.875,0.375,0.719101,7.704120,0.056180,0.011236
2,Derrick Henry,BAL,RB,9200,CIN,Active,2024,5,2,25.0125,...,0,18.625,27.875,231.875,1.875,0.250,0.668161,8.318386,0.067265,0.008969
3,Nico Collins,HOU,WR,8800,BUF,Active,2024,5,3,26.9750,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Jordan Mason,SF,RB,8700,ARI,Active,2024,5,4,28.2475,...,0,21.500,32.250,266.750,1.250,0.375,0.666667,8.271318,0.038760,0.011628

In [22]:
dk_flex_df.head()

,name,team,position,salary,opponent,status,season,week,index,DK_Pts_RB_DvP,...,pos_WR,qb_comp,qb_att,qb_yds,qb_pass_td,qb_int,qb_comp_pct,qb_yds_per_att,qb_td_pct,qb_int_pct
0,Ja'Marr Chase,CIN,WR,8000,BAL,Active,2024.0,5,0,21.8250,...,1.0,24.000,33.375,257.125,1.875,0.375,0.719101,7.704120,0.056180,0.011236
1,Derrick Henry,BAL,RB,7800,CIN,Active,2024.0,5,2,25.0125,...,0.0,18.625,27.875,231.875,1.875,0.250,0.668161,8.318386,0.067265,0.008969
2,Nico Collins,HOU,WR,7700,BUF,Active,2024.0,5,3,26.9750,...,1.0,21.625,31.375,247.500,1.500,0.250,0.689243,7.888446,0.047809,0.007968
3,Tyreek Hill,MIA,WR,7600,NE,Active,2024.0,5,5,25.3200,...,1.0,8.250,13.625,81.875,0.750,0.250,0.605505,6.009174,0.055046,0.018349
4,Kyren Williams,LAR,RB,7600,GB,Active,2024.0,5,6,22.2875,...,0.0,23.375,33.375,281.000,1.125,0.500,0.700375,8.419476,0.033708,0.014981

In [23]:
# fd_flex_df = fd_flex_df.drop(columns = ['index'])
# dk_flex_df = dk_flex_df.drop(columns = ['index'])

In [24]:
fd_flex_df.describe().T

,count,mean,std,min,25%,50%,75%,max
salary,546.0,4543.406593,986.404149,4000.000000,4000.000000,4000.000000,4700.000000,9400.000000
season,546.0,2024.000000,0.000000,2024.000000,2024.000000,2024.000000,2024.000000,2024.000000
week,546.0,5.000000,0.000000,5.000000,5.000000,5.000000,5.000000,5.000000
index,546.0,298.086081,173.236133,0.000000,150.250000,296.000000,448.750000,602.000000
DK_Pts_RB_DvP,546.0,24.364066,3.127628,16.450000,22.125000,24.800000,26.975000,30.250000
DK_Pts_TE_DvP,546.0,11.416209,2.256769,7.262500,9.862500,11.937500,12.600000,16.312500
DK_Pts_WR_DvP,546.0,33.000160,5.041076,24.162500,29.750000,32.950000,35.125000,47.300000
FD_Pts_RB_DvP,546.0,21.149322,3.023225,13.762500,18.912500,21.050000,24.225000,26.187500
FD_Pts_TE_DvP,546.0,8.986493,1.893813,5.262500,7.762500,9.437500,9.912500,13.625000
FD_Pts_WR_DvP,546.0,26.466392,4.160876,19.162500,23.762500,26.832500,28.700000,38.425000
rushing_yards_L8,546.0,7.826074,15.741919,-1.000000,0.000000,1.396698,3.843750,96.500000
rushing_tds_L8,546.0,0.053158,0.132837,0.000000,0.000000,0.000000,0.011241,1.250000
rushing_fumbles_lost_L8,546.0,0.007454,0.029337,0.000000,0.000000,0.000000,0.002027,0.375000
receptions_L8,546.0,2.181708,1.251329,0.000000,1.169643,2.187500,3.088227,8.000000
receiving_yards_L8,546.0,23.749014,17.162611,0.000000,10.656250,20.000000,38.882402,116.000000
receiving_tds_L8,546.0,0.138538,0.147589,0.000000,0.000000,0.125000,0.227402,1.000000
receiving_fumbles_lost_L8,546.0,0.013292,0.034623,0.000000,0.000000,0.000000,0.020542,0.500000
targets_L8,546.0,3.274206,1.861062,0.000000,1.875000,3.062500,4.869456,11.250000
carries_L8,546.0,1.818103,3.635743,0.000000,0.000000,0.228761,0.875000,19.375000
receiving_yards_after_catch_L8,546.0,10.862520,6.794556,0.000000,5.781250,12.104155,13.234321,52.125000
receiving_air_yards_L8,546.0,26.661172,25.081550,-9.875000,2.437500,23.122637,51.834454,140.375000
target_share_L8,546.0,0.102814,0.056821,0.000000,0.057107,0.105155,0.150889,0.320559
carry_share_L8,546.0,0.069788,0.138272,0.000000,0.000000,0.008811,0.031125,0.770125
in_10_share_L8,546.0,0.073344,0.079938,0.000000,0.015885,0.062500,0.072719,0.596875
yards_per_carry_L8,546.0,3.110632,3.142650,-4.000000,0.000000,3.062741,6.105485,24.000000
yards_per_reception_L8,546.0,9.974270,4.431386,0.000000,7.204189,10.367591,12.590525,47.000000
yards_per_target_L8,546.0,6.658241,2.718923,0.000000,5.509615,7.272535,7.984958,23.500000
wind,546.0,6.708791,4.953490,0.000000,4.000000,5.000000,10.000000,17.000000
div_game,546.0,0.459707,0.498831,0.000000,0.000000,0.000000,1.000000,1.000000
spread_line,546.0,-0.043040,3.937992,-7.500000,-3.000000,-1.500000,3.000000,7.500000
total_line,546.0,43.668498,4.690122,35.500000,40.500000,43.500000,48.500000,49.500000
outdoors,546.0,0.831502,0.374651,0.000000,1.000000,1.000000,1.000000,1.000000
grass,546.0,0.547619,0.498184,0.000000,0.000000,1.000000,1.000000,1.000000
home_team,546.0,0.483516,0.500186,0.000000,0.000000,0.000000,1.000000,1.000000
pred_total,546.0,21.812729,3.049527,16.500000,19.000000,22.000000,24.250000,28.500000
opp_total,546.0,21.855769,3.074557,16.500000,19.000000,22.750000,24.250000,28.500000
pos_RB,546.0,0.254579,0.436024,0.000000,0.000000,0.000000,1.000000,1.000000
pos_TE,546.0,0.245421,0.430731,0.000000,0.000000,0.000000,0.000000,1.000000
pos_WR,546.0,0.500000,0.500459,0.000000,0.000000,0.500000,1.000000,1.000000
qb_comp,523.0,18.732314,5.413061,6.000000,17.000000,20.250000,21.750000,26.750000
qb_att,523.0,28.776052,7.538837,8.750000,27.875000,29.875000,33.375000,39.375000
qb_yds,523.0,197.074331,62.387925,66.625000,160.312500,207.250000,231.875000,294.000000
qb_pass_td,523.0,1.027964,0.590900,0.250000,0.562500,0.875000,1.500000,2.125000
qb_int,523.0,0.560229,0.253364,0.125000,0.375000,0.500000,0.750000,1.000000
qb_comp_pct,523.0,0.648267,0.063960,0.532847,0.609235,0.661088,0.680672,0.820755
qb_yds_per_att,523.0,6.840590,1.142846,4.782609,5.812000,7.062500,7.645963,8.462264
qb_td_pct,523.0,0.034938,0.016180,0.007246,0.026786,0.036000,0.040404,0.067265
qb_int_pct,523.0,0.019932,0.008698,0.008065,0.012605,0.017857,0.027875,0.043478

In [25]:
dk_flex_df.describe().T

,count,mean,std,min,25%,50%,75%,max
salary,361.0,3812.742382,1283.637826,2500.000000,3000.000000,3200.000000,4400.000000,8000.000000
season,360.0,2024.000000,0.000000,2024.000000,2024.000000,2024.000000,2024.000000,2024.000000
week,361.0,5.000000,0.000000,5.000000,5.000000,5.000000,5.000000,5.000000
index,361.0,206.542936,118.074124,0.000000,104.000000,207.000000,309.000000,409.000000
DK_Pts_RB_DvP,361.0,24.646419,2.593860,20.600000,22.287500,24.632194,26.950000,30.250000
DK_Pts_TE_DvP,361.0,11.539450,2.310528,7.262500,9.862500,11.937500,12.600000,16.312500
DK_Pts_WR_DvP,361.0,33.174636,5.330401,24.162500,29.750000,32.950000,35.825000,47.300000
FD_Pts_RB_DvP,361.0,21.383776,2.536273,17.437500,19.375000,21.050000,23.825000,26.187500
FD_Pts_TE_DvP,361.0,9.058584,1.945149,5.262500,7.762500,9.437500,9.800000,13.625000
FD_Pts_WR_DvP,361.0,26.652012,4.384788,19.162500,23.937500,27.262500,28.725000,38.425000
rushing_yards_L8,361.0,8.403948,16.978968,-0.500000,0.000000,0.625000,5.000000,96.500000
rushing_tds_L8,361.0,0.057322,0.149928,0.000000,0.000000,0.000000,0.011241,1.250000
rushing_fumbles_lost_L8,361.0,0.008129,0.034181,0.000000,0.000000,0.000000,0.000415,0.375000
receptions_L8,361.0,2.157341,1.332201,0.000000,1.125000,2.000000,3.088227,8.000000
receiving_yards_L8,361.0,23.204546,17.890019,0.000000,10.125000,19.000000,38.882402,116.000000
receiving_tds_L8,361.0,0.137574,0.163224,0.000000,0.000000,0.125000,0.227402,1.000000
receiving_fumbles_lost_L8,361.0,0.011898,0.029777,0.000000,0.000000,0.000000,0.011642,0.125000
targets_L8,361.0,3.297384,2.125847,0.000000,1.750000,2.875000,4.869456,13.000000
carries_L8,361.0,2.010981,3.978562,0.000000,0.000000,0.125000,1.000000,19.375000
receiving_yards_after_catch_L8,361.0,10.889404,7.263700,0.000000,5.500000,11.250000,13.729640,47.250000
receiving_air_yards_L8,361.0,25.522128,26.199305,-9.875000,1.875000,18.875000,49.000000,140.375000
target_share_L8,361.0,0.104040,0.065081,0.000000,0.054156,0.095884,0.150889,0.360000
carry_share_L8,361.0,0.077624,0.152910,0.000000,0.000000,0.007000,0.045000,0.770125
in_10_share_L8,361.0,0.074980,0.087284,0.000000,0.013875,0.061770,0.089750,0.596875
yards_per_carry_L8,361.0,2.833518,3.377343,-4.000000,0.000000,1.980615,4.729167,24.000000
yards_per_reception_L8,361.0,9.800928,4.713500,0.000000,7.204189,10.125000,12.590525,47.000000
yards_per_target_L8,361.0,6.609760,2.937073,0.000000,5.103448,7.000000,7.984958,23.500000
wind,361.0,6.241719,5.051946,0.000000,4.000000,5.000000,10.000000,17.000000
div_game,361.0,0.508340,0.499931,0.000000,0.000000,1.000000,1.000000,1.000000
spread_line,361.0,0.038811,3.924622,-7.000000,-3.000000,1.000000,3.000000,7.000000
total_line,361.0,43.735479,4.813316,35.500000,41.000000,45.500000,48.500000,49.000000
outdoors,361.0,0.802779,0.397902,0.000000,1.000000,1.000000,1.000000,1.000000
grass,361.0,0.502814,0.499993,0.000000,0.000000,1.000000,1.000000,1.000000
home_team,361.0,0.511080,0.499877,0.000000,0.000000,1.000000,1.000000,1.000000
pred_total,361.0,21.887145,3.067169,16.500000,19.000000,23.000000,24.250000,27.750000
opp_total,361.0,21.848334,3.142897,16.500000,18.500000,23.000000,24.000000,27.750000
pos_RB,361.0,0.265943,0.442431,0.000000,0.000000,0.000000,1.000000,1.000000
pos_TE,361.0,0.268698,0.443898,0.000000,0.000000,0.000000,1.000000,1.000000
pos_WR,361.0,0.465359,0.499476,0.000000,0.000000,0.000000,1.000000,1.000000
qb_comp,360.0,20.002431,4.192564,8.250000,19.750000,21.125000,21.750000,25.250000
qb_att,360.0,30.263889,6.222228,13.625000,27.875000,31.375000,34.406250,38.625000
qb_yds,360.0,212.426736,55.365094,81.875000,181.625000,217.625000,257.125000,281.000000
qb_pass_td,360.0,1.244444,0.558132,0.250000,0.750000,1.250000,1.625000,2.500000
qb_int,360.0,0.552778,0.304177,0.125000,0.250000,0.500000,0.750000,1.250000
qb_comp_pct,360.0,0.661064,0.052578,0.571429,0.618123,0.665455,0.689243,0.820755
qb_yds_per_att,360.0,6.993156,1.084795,4.782609,6.009174,7.055319,7.963636,8.462264
qb_td_pct,360.0,0.041573,0.016106,0.007246,0.033708,0.040363,0.054622,0.072727
qb_int_pct,360.0,0.017548,0.007408,0.007968,0.011236,0.016260,0.021818,0.032362

In [26]:
#dk_flex_df[dk_flex_df.isna().any(axis = 1)]

In [27]:
def change_value(df, name, feature, new_value):
    df.loc[df[name] == name, feature] = new_value
    return df

In [28]:
change_def = input('Do you want to change any values in the def dataframes? ')
while change_def == 'y':
    site = input('Which site? ')
    name = input('Which player? ')
    feature = input('Which feature? ')
    new_value = float(input('Enter new value '))
    if site == 'FD':
        fd_def_df = change_value(fd_def_df, name, feature, new_value)
    else:
        dk_def_df = change_value(dk_def_df, name, feature, new_value)
    change_def = ('Do you want to change any other values in the QB dataframes? ')
    
change_qb = input('Do you want to change any values in the QB dataframes? ')
while change_qb == 'y':
    site = input('Which site? ')
    name = input('Which player? ')
    feature = input('Which feature? ')
    new_value = float(input('Enter new value '))
    if site == 'FD':
        fd_qb_df = change_value(fd_qb_df, name, feature, new_value)
    else:
        dk_qb_df = change_value(dk_qb_df, name, feature, new_value)
    change_qb = ('Do you want to change any other values in the QB dataframes? ')

change_flex = input('Do you want to change any values in the FLEX dataframes? ')
while change_flex == 'y':
    site = input('Which site? ')
    name = input('Which player? ')
    feature = input('Which feature? ')
    new_value = float(input('Enter new value '))
    if site == 'FD':
        fd_flex_df = change_value(fd_flex_df, name, feature, new_value)
    else:
        dk_flex_df = change_value(dk_flex_df, name, feature, new_value)
    change_flex = ('Do you want to change any other values in the QB dataframes? ')

fd_def_cols = list(fd_def_df.columns)
dk_def_cols = list(dk_def_df.columns)
fd_qb_cols = list(fd_qb_df.columns)
dk_qb_cols = list(dk_qb_df.columns)
fd_flex_cols = list(fd_flex_df.columns)
dk_flex_cols = list(dk_flex_df.columns)

def_x_cols = ['spread_line',
 'home_team',
 'outdoors',
 'grass',
 'total_line',
 'opp_total',
 'opp_vs_def_L8',
 'opp_vs_def_L8_lin',
 'opp_vs_def_L8_exp']

qb_x_cols = ['FD_Pts_DvP', 'DK_Pts_DvP', 'QB_role', 'completions_L8', 'attempts_L8',
       'passing_yards_L8', 'passing_tds_L8', 'interceptions_L8', 'sacks_L8',
       'passing_air_yards_L8', 'pacr_L8', 'carries_L8', 'rushing_yards_L8',
       'rushing_tds_L8', 'comp_pct', 'yds_per_attempt', 'td_pct', 'sack_pct',
       'int_pct', 'wind', 'div_game', 'spread_line', 'total_line', 'outdoors',
       'grass', 'home_team', 'pred_total', 'opp_total']

flex_x_cols = ['DK_Pts_RB_DvP', 'DK_Pts_TE_DvP', 'DK_Pts_WR_DvP', 'FD_Pts_RB_DvP',
       'FD_Pts_TE_DvP', 'FD_Pts_WR_DvP', 'rushing_yards_L8', 'rushing_tds_L8',
       'rushing_fumbles_lost_L8', 'receptions_L8', 'receiving_yards_L8',
       'receiving_tds_L8', 'receiving_fumbles_lost_L8', 'targets_L8',
       'carries_L8', 'receiving_yards_after_catch_L8',
       'receiving_air_yards_L8', 'target_share_L8', 'carry_share_L8',
       'in_10_share_L8', 'yards_per_carry_L8', 'yards_per_reception_L8',
       'yards_per_target_L8', 'wind', 'div_game', 'spread_line', 'total_line',
       'outdoors', 'grass', 'home_team', 'pred_total', 'opp_total', 'qb_comp',
       'qb_att', 'qb_yds', 'qb_pass_td', 'qb_int', 'qb_comp_pct',
       'qb_yds_per_att', 'qb_td_pct', 'qb_int_pct', 'pos_RB', 'pos_TE',
       'pos_WR']

# List of dataframes
df_list = {
    'fd_def_df': fd_def_df,
    'fd_qb_df': fd_qb_df,
    'fd_flex_df': fd_flex_df,
    'dk_def_df': dk_def_df,
    'dk_qb_df': dk_qb_df,
    'dk_flex_df': dk_flex_df
}

# List to store whether each dataframe has missing values
missing_bool_list = []

# Check for missing values in each dataframe and store in the list
# for df in df_list:
#     missing_values = df.isnull().any().any()  # Check for any missing values
#     missing_bool_list.append(missing_values)

for df_name, df in df_list.items():
    missing_values = df.isnull().any().any()  # Check for any missing values
    missing_bool_list.append((df_name, missing_values))

# Create a dictionary mapping each dataframe to its missing value status
missing_dict = dict(missing_bool_list)

# Iterate over the dictionary to handle dataframes with missing values
# Iterate over the dictionary to handle dataframes with missing values
for df_name, has_missing in missing_dict.items():
    if has_missing:
        print(f"{df_name} has missing values")

        # Specify which columns have missing values
        missing_columns = df_list[df_name].columns[df_list[df_name].isna().any()].tolist()
        print(f"Columns with missing values in {df_name}: {missing_columns}")

        # Display rows with missing values
        display(df_list[df_name][df_list[df_name].isna().any(axis=1)])

        # Allow the user to fill missing values
        fill = input('Do you want to fill a value? ').lower()
        while fill == 'y':
            col = input(f"Which column do you want to fill? Choose from {missing_columns}: ")
            name = input('Which player? ')
            new_value = float(input('Enter new value: '))
    
            # Update the dataframe where the 'name' column matches the input player name
            df_list[df_name].loc[df_list[df_name]['name'] == name, col] = new_value
            fill = input('Do you want to fill another value? (y/n) ').lower()

fd_def_df = fd_def_df.dropna()
fd_qb_df = fd_qb_df.dropna()
fd_flex_df = fd_flex_df.dropna()
dk_def_df = dk_def_df.dropna()
dk_qb_df = dk_qb_df.dropna()
dk_flex_df = dk_flex_df.dropna()

fd_def_df = fd_def_df.set_index(['name', 'team', 'position', 'salary', 'opponent', 'status', 'season', 'week'])
dk_def_df = dk_def_df.set_index(['name', 'team', 'position', 'salary', 'opponent', 'status', 'season', 'week'])
fd_qb_df = fd_qb_df.set_index(['name', 'team', 'position', 'salary', 'opponent', 'status', 'season', 'week'])
dk_qb_df = dk_qb_df.set_index(['name', 'team', 'position', 'salary', 'opponent', 'status', 'season', 'week'])
fd_flex_df = fd_flex_df.set_index(['name', 'team', 'position', 'salary', 'opponent', 'status', 'season', 'week'])
dk_flex_df = dk_flex_df.set_index(['name', 'team', 'position', 'salary', 'opponent', 'status', 'season', 'week'])

fd_flex_df = fd_flex_df[flex_x_cols]
dk_flex_df = dk_flex_df[flex_x_cols]
fd_qb_df = fd_qb_df[qb_x_cols]
dk_qb_df = dk_qb_df[qb_x_cols]
fd_def_df = fd_def_df[def_x_cols]
dk_def_df = dk_def_df[def_x_cols]

all_conditions = all([
    list(fd_def_df.columns) == def_x_cols,
    list(dk_def_df.columns) == def_x_cols,
    list(fd_qb_df.columns) == qb_x_cols,
    list(dk_qb_df.columns) == qb_x_cols,
    list(fd_flex_df.columns) == flex_x_cols,
    list(dk_flex_df.columns) == flex_x_cols
])

if not all_conditions:
    print("Not all column orders match training data.")

change_datasets = input('Did dataset values change? ')
if change_datasets == 'y':
    fd_flex_df.to_csv('FD_FLEX_for_model_' + str(season) + '_' + str(week) + '.csv')
    dk_flex_df.to_csv('DK_FLEX_for_model_' + str(season) + '_' + str(week) + '.csv')
    fd_qb_df.to_csv('FD_qb_for_model_' + str(season) + '_' + str(week) + '.csv')
    dk_qb_df.to_csv('DK_qb_for_model_' + str(season) + '_' + str(week) + '.csv')
    fd_def_df.to_csv('FD_def_for_model_' + str(season) + '_' + str(week) + '.csv')
    dk_def_df.to_csv('DK_def_for_model_' + str(season) + '_' + str(week) + '.csv')

Do you want to change any values in the def dataframes?  n
Do you want to change any values in the QB dataframes?  n
Do you want to change any values in the FLEX dataframes?  n

fd_flex_df has missing values
Columns with missing values in fd_flex_df: ['qb_comp', 'qb_att', 'qb_yds', 'qb_pass_td', 'qb_int', 'qb_comp_pct', 'qb_yds_per_att', 'qb_td_pct', 'qb_int_pct']

,name,team,position,salary,opponent,status,season,week,index,DK_Pts_RB_DvP,...,pos_WR,qb_comp,qb_att,qb_yds,qb_pass_td,qb_int,qb_comp_pct,qb_yds_per_att,qb_td_pct,qb_int_pct
3,Nico Collins,HOU,WR,8800,BUF,Active,2024,5,3,26.975,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Stefon Diggs,HOU,WR,7600,BUF,Active,2024,5,17,26.975,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Cam Akers,HOU,RB,6200,BUF,Active,2024,5,42,26.975,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Tank Dell,HOU,WR,6000,BUF,Active,2024,5,55,26.975,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,Dalton Schultz,HOU,TE,5400,BUF,Active,2024,5,93,26.975,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,Dameon Pierce,HOU,RB,5300,BUF,Q,2024,5,97,26.975,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,Dare Ogunbowale,HOU,RB,5000,BUF,Active,2024,5,126,26.975,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,Robert Woods,HOU,WR,4800,BUF,Q,2024,5,148,26.975,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,JJ Taylor,HOU,RB,4500,BUF,Active,2024,5,167,26.975,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,Cade Stover,HOU,TE,4400,BUF,Active,2024,5,172,26.975,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,John Metchie,HOU,WR,4200,BUF,Active,2024,5,206,26.975,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,Xavier Hutchinson,HOU,WR,4200,BUF,Active,2024,5,223,26.975,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,British Brooks,HOU,RB,4100,BUF,Active,2024,5,232,26.975,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,Irv Smith,HOU,TE,4000,BUF,Active,2024,5,247,26.975,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
317,Troy Hairston,HOU,RB,4000,BUF,Active,2024,5,345,26.975,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,Johnny Johnson,HOU,WR,4000,BUF,Active,2024,5,370,26.975,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
370,Jared Wayne,HOU,WR,4000,BUF,Q,2024,5,405,26.975,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
385,Steven Sims,HOU,WR,4000,BUF,Active,2024,5,421,26.975,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
391,Jaxon Janke,HOU,WR,4000,BUF,Q,2024,5,427,26.975,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
419,Chris Myarick,HOU,TE,4000,BUF,Active,2024,5,461,26.975,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
455,Nick Bawden,HOU,RB,4000,BUF,Active,2024,5,498,26.975,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
517,Jawhar Jordan,HOU,RB,4000,BUF,Q,2024,5,569,26.975,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
536,Xavier Johnson,HOU,WR,4000,BUF,Active,2024,5,592,26.975,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Do you want to fill a value?  n

dk_flex_df has missing values
Columns with missing values in dk_flex_df: ['season', 'qb_comp', 'qb_att', 'qb_yds', 'qb_pass_td', 'qb_int', 'qb_comp_pct', 'qb_yds_per_att', 'qb_td_pct', 'qb_int_pct']

,name,team,position,salary,opponent,status,season,week,index,DK_Pts_RB_DvP,...,pos_WR,qb_comp,qb_att,qb_yds,qb_pass_td,qb_int,qb_comp_pct,qb_yds_per_att,qb_td_pct,qb_int_pct
203,Malik Cunningham,BAL,WR,3000,CIN,Active,NaN,5,231,24.632194,...,0.994681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Do you want to fill a value?  n
Did dataset values change?  y

In [ ]:
# dk_flex_df.loc[dk_flex_df['name'] == 'Sione Vaki', 'pos_RB'] = 1
# dk_flex_df.loc[dk_flex_df['name'] == 'Sione Vaki', 'pos_WR'] = 0
# dk_flex_df.loc[dk_flex_df['name'] == 'Sione Vaki', 'pos_TE'] = 0

# dk_flex_df.loc[dk_flex_df['name'] == 'Zach Wood', 'pos_RB'] = 0
# dk_flex_df.loc[dk_flex_df['name'] == 'Zach Wood', 'pos_WR'] = 0
# dk_flex_df.loc[dk_flex_df['name'] == 'Zach Wood', 'pos_TE'] = 1

# dk_flex_df.loc[dk_flex_df['name'] == 'Evan Deckers', 'pos_RB'] = 0
# dk_flex_df.loc[dk_flex_df['name'] == 'Evan Deckers', 'pos_WR'] = 0
# dk_flex_df.loc[dk_flex_df['name'] == 'Evan Deckers', 'pos_TE'] = 1

# dk_flex_df.loc[dk_flex_df['name'] == 'Malik Cunningham', 'pos_RB'] = 0
# dk_flex_df.loc[dk_flex_df['name'] == 'Malik Cunningham', 'pos_WR'] = 1
# dk_flex_df.loc[dk_flex_df['name'] == 'Malik Cunningham', 'pos_TE'] = 0

In [ ]:
###Checking proper column order

In [ ]:
# fd_qb_df.head()

In [ ]:
# dk_qb_df.head()

In [ ]:
# fd_def_df.head()

In [ ]:
# dk_def_df.head()

In [ ]:
# fd_flex_df.head()

In [ ]:
# dk_flex_df.head()

In [ ]:
# fd_def_df.info()

In [ ]:
# dk_def_df.info()

In [ ]:
# fd_qb_df.info()

In [ ]:
# dk_qb_df.info()

In [ ]:
# fd_flex_df.info()

In [ ]:
# dk_flex_df.info()

In [ ]:


# missing_bool_list = []
# df_list = [fd_def_df, fd_qb_df, fd_flex_df, dk_def_df, dk_qb_df, dk_flex_df]

# for df in df_list:
#     missing_values = df.isnull().any().any()
#     missing_bool_list.append(missing_values)

# missing_dict = dict(list(zip(df_list, missing_bool_list)))

# for k, v in missing_dict.items():
#     if v == True:
#         print(f"{k} has missing values")
#         df[df.isna().any(axis = 1)]
#         col = input('Which column do you want to fill? ')
#         name = input('Which player? ')
#         new_value = float(input('Enter new value: '))
#         df.loc[df['name'] == name, col] = new_value

In [ ]:
# dk_flex_df[dk_flex_df.isna().any(axis = 1)]

In [ ]:
# dk_flex_df.info()

In [ ]:
# fd_flex_df.head()

In [ ]:
# dk_flex_df.head()

In [ ]:
# fd_def_df.head()

In [ ]:
# dk_def_df.head()

In [85]:
fd_flex_df.head()

,name,team,position,salary,opponent,status,season,week,index,DK_Pts_RB_DvP,...,pos_WR,qb_comp,qb_att,qb_yds,qb_pass_td,qb_int,qb_comp_pct,qb_yds_per_att,qb_td_pct,qb_int_pct
0,Saquon Barkley,PHI,RB,9700,TB,Active,2024,4,0,22.2875,...,0,20.375,30.625,211.000,1.000,1.125,0.665306,6.889796,0.032653,0.036735
1,Justin Jefferson,MIN,WR,9400,GB,Active,2024,4,1,21.7500,...,1,9.875,15.125,118.375,1.250,0.375,0.652893,7.826446,0.082645,0.024793
2,Ja'Marr Chase,CIN,WR,9200,CAR,Active,2024,4,2,24.0500,...,1,24.250,33.875,251.250,1.875,0.375,0.715867,7.416974,0.055351,0.011070
3,Jordan Mason,SF,RB,8800,NE,Active,2024,4,3,23.6450,...,0,21.875,32.875,262.625,1.125,0.750,0.665399,7.988593,0.034221,0.022814
4,Alvin Kamara,NO,RB,8600,ATL,Q,2024,4,4,22.0500,...,0,19.750,27.250,212.750,2.500,0.500,0.724771,7.807339,0.091743,0.018349

In [86]:
fd_flex_df[fd_flex_df['team'] == 'PIT']

,name,team,position,salary,opponent,status,season,week,index,DK_Pts_RB_DvP,...,pos_WR,qb_comp,qb_att,qb_yds,qb_pass_td,qb_int,qb_comp_pct,qb_yds_per_att,qb_td_pct,qb_int_pct
37,Najee Harris,PIT,RB,6600,IND,Active,2024,4,42,26.1125,...,0,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
56,George Pickens,PIT,WR,6100,IND,Active,2024,4,62,26.1125,...,1,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
131,Pat Freiermuth,PIT,TE,5000,IND,Active,2024,4,144,26.1125,...,0,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
147,Calvin Austin III,PIT,WR,4900,IND,Active,2024,4,160,26.1125,...,1,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
170,Cordarrelle Patterson,PIT,RB,4700,IND,Active,2024,4,183,26.1125,...,0,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
172,Darnell Washington,PIT,TE,4700,IND,Active,2024,4,185,26.1125,...,0,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
186,Van Jefferson,PIT,WR,4600,IND,Active,2024,4,199,26.1125,...,1,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
194,Roman Wilson,PIT,WR,4500,IND,Active,2024,4,207,26.1125,...,1,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
208,Scotty Miller,PIT,WR,4400,IND,Active,2024,4,223,26.1125,...,1,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
225,Connor Heyward,PIT,TE,4200,IND,Active,2024,4,240,26.1125,...,0,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
257,Jacob Copeland,PIT,WR,4000,IND,Active,2024,4,273,26.1125,...,1,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
298,Rodney Williams,PIT,TE,4000,IND,Active,2024,4,317,26.1125,...,0,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
306,Aaron Shampklin,PIT,RB,4000,IND,Active,2024,4,325,26.1125,...,0,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
332,Daijun Edwards,PIT,RB,4000,IND,Active,2024,4,354,26.1125,...,0,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
346,Boston Scott,PIT,RB,4000,IND,Q,2024,4,370,26.1125,...,0,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
365,Duece Watts,PIT,WR,4000,IND,Active,2024,4,389,26.1125,...,1,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
442,Jack Colletto,PIT,RB,4000,IND,Active,2024,4,476,26.1125,...,0,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
470,Matt Sokol,PIT,TE,4000,IND,Active,2024,4,508,26.1125,...,0,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
513,Shaquan Davis,PIT,WR,4000,IND,Active,2024,4,557,26.1125,...,1,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
516,Keilahn Harris,PIT,WR,4000,IND,Q,2024,4,560,26.1125,...,1,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
517,Tarik Black,PIT,WR,4000,IND,Q,2024,4,561,26.1125,...,1,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
549,Jonathan Ward,PIT,RB,4000,IND,Active,2024,4,598,26.1125,...,0,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
580,Brandon Johnson,PIT,WR,4000,IND,Active,2024,4,633,26.1125,...,1,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
621,Jaray Jenkins,PIT,WR,4000,IND,Active,2024,4,676,26.1125,...,1,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
636,Godwin Igwebuike,PIT,RB,4000,IND,Active,2024,4,695,26.1125,...,0,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937
667,Quez Watkins,PIT,WR,4000,IND,Active,2024,4,732,26.1125,...,1,17.375,27.875,186.625,0.75,0.5,0.623318,6.695067,0.026906,0.017937