# EDA

In [1]:
import numpy as np
import pandas as pd
#import pickle
from IPython.display import display
from functions import get_current_weekday, calculate_nfl_week, get_next_sunday, get_current_year

In [2]:
day = get_current_weekday()

In [3]:
date_string = get_next_sunday(day)

In [4]:
week = calculate_nfl_week(date_string)

In [5]:
season = get_current_year()

In [6]:
pd.set_option('display.max_rows', None)

In [7]:
fd_def_df = pd.read_csv('FD_def_for_model_' + str(season) + '_' + str(week) + '.csv')
dk_def_df = pd.read_csv('DK_def_for_model_' + str(season) + '_' + str(week) + '.csv')

In [8]:
fd_def_df.head()

,position,salary,team,opponent,date,week,season,spread_line,home_team,outdoors,grass,total_line,opp_total,opp_vs_def_L8,opp_vs_def_L8_lin,opp_vs_def_L8_exp
0,D,5000,BUF,TEN,10-20-2024,7,2024,8.5,1,1,0,41.5,16.50,10.750,9.32,7.810
1,D,4900,CIN,CLE,10-20-2024,7,2024,5.5,0,1,1,41.5,18.00,11.625,11.11,10.585
2,D,4800,NYJ,PIT,10-20-2024,7,2024,1.5,0,1,1,38.5,18.50,5.500,5.18,4.710
3,D,4700,PHI,NYG,10-20-2024,7,2024,3.0,0,1,0,43.5,20.25,8.375,8.36,8.130
4,D,4600,WAS,CAR,10-20-2024,7,2024,8.5,1,1,1,51.5,21.50,9.875,7.47,7.375

In [9]:
dk_def_df.head()

,position,salary,team,opponent,date,week,season,spread_line,home_team,outdoors,grass,total_line,opp_total,opp_vs_def_L8,opp_vs_def_L8_lin,opp_vs_def_L8_exp
0,D,3600,PHI,NYG,10-20-2024,7,2024,3.0,0,1,0,43.0,20.00,8.375,8.36,8.130
1,D,3500,BUF,TEN,10-20-2024,7,2024,9.0,1,1,0,41.0,16.00,10.750,9.32,7.810
2,D,3400,WAS,CAR,10-20-2024,7,2024,8.0,1,1,1,52.0,22.00,9.875,7.47,7.375
3,D,3300,CIN,CLE,10-20-2024,7,2024,6.0,0,1,1,41.5,17.75,11.625,11.11,10.585
4,D,3200,IND,MIA,10-20-2024,7,2024,3.0,1,0,0,NaN,NaN,10.375,10.84,10.100

In [10]:
fd_def_df = fd_def_df.drop(columns = ['date'])
dk_def_df = dk_def_df.drop(columns = ['date'])

In [11]:
fd_def_df['name'] = fd_def_df['team']
dk_def_df['name'] = dk_def_df['team']

In [12]:
fd_def_df['status'] = 'Active'
dk_def_df['status'] = 'Active'

In [13]:
fd_def_df.describe().T

,count,mean,std,min,25%,50%,75%,max
salary,22.0,4000.000000,605.530071,3000.000,3525.00000,4000.0000,4475.00000,5000.000
week,22.0,7.000000,0.000000,7.000,7.00000,7.0000,7.00000,7.000
season,22.0,2024.000000,0.000000,2024.000,2024.00000,2024.0000,2024.00000,2024.000
spread_line,22.0,0.000000,4.947342,-8.500,-3.00000,0.0000,3.00000,8.500
home_team,22.0,0.500000,0.511766,0.000,0.00000,0.5000,1.00000,1.000
outdoors,22.0,0.636364,0.492366,0.000,0.00000,1.0000,1.00000,1.000
grass,22.0,0.545455,0.509647,0.000,0.00000,1.0000,1.00000,1.000
total_line,22.0,45.500000,4.342481,38.500,42.00000,43.5000,49.75000,51.500
opp_total,22.0,22.750000,3.291403,16.500,20.25000,23.2500,24.87500,30.000
opp_vs_def_L8,22.0,6.704545,2.617633,2.625,4.71875,6.0000,8.31250,11.625
opp_vs_def_L8_lin,22.0,6.682273,2.804104,2.200,4.61500,6.5400,8.57000,11.820
opp_vs_def_L8_exp,22.0,6.337500,2.835679,1.620,4.20000,6.2875,8.48625,11.870

In [14]:
dk_def_df.describe().T

,count,mean,std,min,25%,50%,75%,max
salary,20.0,2910.000000,371.200045,2300.000,2600.00000,2900.0000,3125.00000,3600.000
week,20.0,7.000000,0.000000,7.000,7.00000,7.0000,7.00000,7.000
season,20.0,2024.000000,0.000000,2024.000,2024.00000,2024.0000,2024.00000,2024.000
spread_line,20.0,0.000000,5.269076,-9.000,-3.00000,0.0000,3.00000,9.000
home_team,20.0,0.500000,0.512989,0.000,0.00000,0.5000,1.00000,1.000
outdoors,20.0,0.600000,0.502625,0.000,0.00000,1.0000,1.00000,1.000
grass,20.0,0.500000,0.512989,0.000,0.00000,0.5000,1.00000,1.000
total_line,18.0,46.388889,4.178219,41.000,43.00000,47.0000,51.00000,52.000
opp_total,18.0,23.194444,3.443403,16.000,22.06250,23.8750,25.00000,30.000
opp_vs_def_L8,20.0,6.706250,2.724848,2.625,4.59375,6.0000,8.53125,11.625
opp_vs_def_L8_lin,20.0,6.662500,2.895159,2.200,4.54500,6.5400,8.58750,11.820
opp_vs_def_L8_exp,20.0,6.303250,2.909538,1.620,4.07250,6.2875,8.24875,11.870

In [15]:
fd_qb_df = pd.read_csv('FD_qb_for_model_' + str(season) + '_' + str(week) + '.csv')
dk_qb_df = pd.read_csv('DK_qb_for_model_' + str(season) + '_' + str(week) + '.csv')

In [16]:
fd_qb_df.head()

,name,team,position,salary,opponent,status,season,week,FD_Pts_DvP,DK_Pts_DvP,...,int_pct,wind,div_game,spread_line,total_line,outdoors,grass,home_team,pred_total,opp_total
0,Josh Allen,BUF,QB,9200,TEN,Active,2024,7,15.3300,15.4550,...,0.000000,8,0,8.5,41.5,1,0,1,25.00,16.50
1,Jayden Daniels,WAS,QB,9100,CAR,Active,2024,7,15.9975,16.5600,...,0.012048,3,0,8.5,51.5,1,1,1,30.00,21.50
2,Jordan Love,GB,QB,8700,HOU,Active,2024,7,20.3450,21.2200,...,0.030075,9,0,2.5,47.5,1,1,1,25.00,22.50
3,Jalen Hurts,PHI,QB,8500,NYG,Active,2024,7,16.5525,17.3025,...,0.025974,3,1,3.0,43.5,1,0,0,23.25,20.25
4,CJ Stroud,HOU,QB,8400,GB,Active,2024,7,17.7300,18.6050,...,0.015267,9,0,-2.5,47.5,1,1,0,22.50,25.00

In [17]:
dk_qb_df.head()

,name,team,position,salary,opponent,status,season,week,FD_Pts_DvP,DK_Pts_DvP,...,int_pct,wind,div_game,spread_line,total_line,outdoors,grass,home_team,pred_total,opp_total
0,Jayden Daniels,WAS,QB,7600,CAR,Active,2024,7,15.9975,16.5600,...,0.012048,3,0,8.0,52.0,1,1,1,30.00,22.00
1,Josh Allen,BUF,QB,7500,TEN,Active,2024,7,15.3300,15.4550,...,0.000000,8,0,9.0,41.0,1,0,1,25.00,16.00
2,Jalen Hurts,PHI,QB,7300,NYG,Active,2024,7,16.5525,17.3025,...,0.025974,3,1,3.0,43.0,1,0,0,23.00,20.00
3,CJ Stroud,HOU,QB,7100,GB,Active,2024,7,17.7300,18.6050,...,0.015267,9,0,-3.0,47.5,1,1,0,22.25,25.25
4,Patrick Mahomes,KC,QB,7000,SF,Active,2024,7,17.3650,18.2400,...,0.026119,3,0,-1.5,47.0,1,1,0,22.75,24.25

In [18]:
fd_qb_df.describe().T

,count,mean,std,min,25%,50%,75%,max
salary,97.0,6384.536082,778.933593,6000.000000,6000.000000,6000.000000,6000.000000,9200.000000
season,97.0,2024.000000,0.000000,2024.000000,2024.000000,2024.000000,2024.000000,2024.000000
week,97.0,7.000000,0.000000,7.000000,7.000000,7.000000,7.000000,7.000000
FD_Pts_DvP,97.0,17.547423,2.050211,11.565000,16.267500,17.465000,18.447500,22.527500
DK_Pts_DvP,97.0,18.238144,2.186928,12.190000,16.790000,18.240000,19.777500,22.777500
QB_role,97.0,1.773196,0.420940,1.000000,2.000000,2.000000,2.000000,2.000000
completions_L8,97.0,15.127444,6.229983,0.000000,11.400000,17.891300,18.000000,26.500000
attempts_L8,97.0,23.727622,9.153376,0.000000,20.250000,27.748797,27.748797,39.250000
passing_yards_L8,97.0,163.756510,70.013824,0.000000,135.750000,195.204964,195.204964,298.125000
passing_tds_L8,97.0,0.893769,0.537324,0.000000,0.428571,1.125000,1.143092,2.750000
interceptions_L8,97.0,0.618558,0.304075,0.000000,0.500000,0.623034,0.750000,1.500000
sacks_L8,97.0,1.881270,0.841526,0.000000,1.500000,2.024215,2.024215,4.500000
passing_air_yards_L8,97.0,182.981365,71.067799,0.000000,156.750000,215.501883,215.501883,330.375000
pacr_L8,97.0,1.013283,0.471908,0.423393,0.829630,0.959662,1.014856,4.500000
carries_L8,97.0,3.268739,1.753969,0.000000,2.000000,3.665955,3.665955,10.500000
rushing_yards_L8,97.0,13.253858,10.237428,-2.500000,4.666667,16.095326,16.095326,53.666667
rushing_tds_L8,97.0,0.132557,0.166351,0.000000,0.000000,0.125000,0.181762,0.750000
comp_pct,97.0,0.636185,0.074814,0.448980,0.616034,0.644759,0.645669,1.000000
yds_per_attempt,97.0,7.166639,3.247551,3.928571,6.196911,7.034718,7.233974,37.000000
td_pct,97.0,0.034962,0.016514,0.000000,0.028674,0.041194,0.041194,0.082707
sack_pct,97.0,0.087011,0.061523,0.000000,0.072917,0.072948,0.090361,0.500000
int_pct,97.0,0.030599,0.032175,0.000000,0.021201,0.022453,0.030888,0.250000
wind,97.0,3.072165,3.139956,0.000000,0.000000,3.000000,6.000000,9.000000
div_game,97.0,0.247423,0.433756,0.000000,0.000000,0.000000,0.000000,1.000000
spread_line,97.0,0.520619,4.751599,-8.500000,-3.000000,1.500000,3.000000,8.500000
total_line,97.0,45.541237,4.429817,38.500000,41.500000,43.500000,50.500000,51.500000
outdoors,97.0,0.639175,0.482735,0.000000,0.000000,1.000000,1.000000,1.000000
grass,97.0,0.567010,0.498063,0.000000,0.000000,1.000000,1.000000,1.000000
home_team,97.0,0.494845,0.502571,0.000000,0.000000,0.000000,1.000000,1.000000
pred_total,97.0,23.030928,3.159447,16.500000,20.250000,23.250000,25.000000,30.000000
opp_total,97.0,22.510309,3.334424,16.500000,20.000000,23.250000,24.500000,30.000000

In [19]:
dk_qb_df.describe().T

,count,mean,std,min,25%,50%,75%,max
salary,67.0,4900.000000,1071.108177,4000.000000,4000.000000,4600.000000,5450.000000,7600.000000
season,67.0,2024.000000,0.000000,2024.000000,2024.000000,2024.000000,2024.000000,2024.000000
week,67.0,7.000000,0.000000,7.000000,7.000000,7.000000,7.000000,7.000000
FD_Pts_DvP,67.0,17.855299,1.634542,15.330000,16.552500,17.730000,18.447500,22.527500
DK_Pts_DvP,67.0,18.591306,1.789494,15.455000,17.210000,18.605000,19.810000,22.777500
QB_role,67.0,1.701493,0.461057,1.000000,1.000000,2.000000,2.000000,2.000000
completions_L8,67.0,14.957628,6.681133,0.500000,11.062500,17.891300,19.375000,26.500000
attempts_L8,67.0,23.333633,9.799442,0.500000,18.750000,27.748797,29.937500,39.250000
passing_yards_L8,67.0,160.567645,76.464009,11.000000,101.783333,180.750000,195.204964,298.125000
passing_tds_L8,67.0,0.881847,0.571552,0.000000,0.380952,0.875000,1.143092,2.750000
interceptions_L8,67.0,0.616261,0.330005,0.000000,0.437500,0.623034,0.750000,1.500000
sacks_L8,67.0,1.886178,0.897596,0.000000,1.375000,2.000000,2.437500,4.500000
passing_air_yards_L8,67.0,179.278429,75.898164,5.000000,142.232143,212.125000,224.000000,330.375000
pacr_L8,67.0,1.023976,0.507677,0.423393,0.819556,0.959662,1.076286,4.500000
carries_L8,67.0,3.136173,1.823121,0.375000,1.937500,3.000000,3.690120,10.500000
rushing_yards_L8,67.0,12.855862,11.124805,-1.125000,4.062500,13.250000,16.172663,53.666667
rushing_tds_L8,67.0,0.120863,0.174877,0.000000,0.000000,0.000000,0.181762,0.750000
comp_pct,67.0,0.641479,0.083093,0.490566,0.605344,0.644759,0.655610,1.000000
yds_per_attempt,67.0,7.232090,3.855015,3.928571,6.008532,7.034718,7.604914,37.000000
td_pct,67.0,0.034770,0.017643,0.000000,0.026872,0.040000,0.042105,0.082707
sack_pct,67.0,0.094143,0.071274,0.000000,0.062587,0.072948,0.099587,0.500000
int_pct,67.0,0.030314,0.031732,0.000000,0.017771,0.022453,0.033781,0.250000
wind,67.0,3.253731,3.281460,0.000000,0.000000,3.000000,6.000000,9.000000
div_game,67.0,0.298507,0.461057,0.000000,0.000000,0.000000,1.000000,1.000000
spread_line,67.0,0.253731,5.156177,-9.000000,-3.000000,1.500000,3.000000,9.000000
total_line,60.0,46.441667,4.086036,41.000000,43.000000,47.000000,51.000000,52.000000
outdoors,67.0,0.611940,0.490986,0.000000,0.000000,1.000000,1.000000,1.000000
grass,67.0,0.507463,0.503718,0.000000,0.000000,1.000000,1.000000,1.000000
home_team,67.0,0.507463,0.503718,0.000000,0.000000,1.000000,1.000000,1.000000
pred_total,60.0,23.387500,3.353289,16.000000,22.187500,24.000000,25.000000,30.000000
opp_total,60.0,23.054167,3.379303,16.000000,22.000000,23.750000,25.000000,30.000000

In [20]:
fd_flex_df = pd.read_csv('FD_FLEX_for_model_' + str(season) + '_' + str(week) + '.csv')
dk_flex_df = pd.read_csv('DK_FLEX_for_model_' + str(season) + '_' + str(week) + '.csv')

In [21]:
fd_flex_df.head()

,name,team,position,salary,opponent,status,season,week,index,DK_Pts_RB_DvP,...,qb_yds,qb_pass_td,qb_int,qb_comp_pct,qb_yds_per_att,qb_td_pct,qb_int_pct,pos_RB,pos_TE,pos_WR
0,Justin Jefferson,MIN,WR,9400,DET,Active,2024,7,0,20.5500,...,172.625,1.625,0.625,0.627119,7.802260,0.073446,0.028249,0,0,1
1,Ja'Marr Chase,CIN,WR,9300,CLE,Active,2024,7,1,21.3750,...,253.250,1.875,0.500,0.705426,7.852713,0.058140,0.015504,0,0,1
2,Saquon Barkley,PHI,RB,9000,NYG,Active,2024,7,2,20.5625,...,208.250,1.250,0.750,0.675325,7.212121,0.043290,0.025974,1,0,0
3,AJ Brown,PHI,WR,8900,NYG,Active,2024,7,3,20.5625,...,208.250,1.250,0.750,0.675325,7.212121,0.043290,0.025974,0,0,1
4,Jordan Mason,SF,RB,8800,KC,Q,2024,7,4,18.1625,...,268.875,1.375,0.625,0.645669,8.468504,0.043307,0.019685,1,0,0

In [22]:
dk_flex_df.head()

,name,team,position,salary,opponent,status,season,week,index,DK_Pts_RB_DvP,...,qb_yds,qb_pass_td,qb_int,qb_comp_pct,qb_yds_per_att,qb_td_pct,qb_int_pct,pos_RB,pos_TE,pos_WR
0,Justin Jefferson,MIN,WR,8500,DET,Active,2024,7,0,20.5500,...,172.625,1.625,0.625,0.627119,7.802260,0.073446,0.028249,0,0,1
1,Ja'Marr Chase,CIN,WR,8400,CLE,Active,2024,7,1,21.3750,...,253.250,1.875,0.500,0.705426,7.852713,0.058140,0.015504,0,0,1
2,Amon-Ra St Brown,DET,WR,8300,MIN,Active,2024,7,2,20.3125,...,270.875,1.500,0.500,0.703846,8.334615,0.046154,0.015385,0,0,1
3,Saquon Barkley,PHI,RB,8200,NYG,Active,2024,7,3,20.5625,...,208.250,1.250,0.750,0.675325,7.212121,0.043290,0.025974,1,0,0
4,Kyren Williams,LAR,RB,8100,LV,Active,2024,7,4,27.4625,...,281.250,1.000,0.625,0.684588,8.064516,0.028674,0.017921,1,0,0

In [23]:
# fd_flex_df = fd_flex_df.drop(columns = ['index'])
# dk_flex_df = dk_flex_df.drop(columns = ['index'])

In [24]:
fd_flex_df.describe().T

,count,mean,std,min,25%,50%,75%,max
salary,561.0,4640.285205,1134.577922,4000.000000,4000.000000,4000.000000,4800.000000,9400.000000
season,561.0,2024.000000,0.000000,2024.000000,2024.000000,2024.000000,2024.000000,2024.000000
week,561.0,7.000000,0.000000,7.000000,7.000000,7.000000,7.000000,7.000000
index,561.0,294.654189,175.245486,0.000000,142.000000,289.000000,446.000000,603.000000
DK_Pts_RB_DvP,561.0,23.307843,3.974360,16.600000,20.550000,23.262500,26.025000,32.237500
DK_Pts_TE_DvP,561.0,11.182843,2.346993,7.950000,9.412500,10.837500,12.625000,17.525000
DK_Pts_WR_DvP,561.0,34.906297,6.523810,22.650000,29.992500,34.625000,38.425000,49.527500
FD_Pts_RB_DvP,561.0,20.388503,3.679597,14.550000,17.812500,19.825000,22.962500,29.175000
FD_Pts_TE_DvP,561.0,8.791689,1.966176,6.187500,7.212500,8.650000,10.362500,14.275000
FD_Pts_WR_DvP,561.0,27.951529,5.022641,18.650000,24.335000,28.050000,31.175000,38.402500
rushing_yards_L8,561.0,8.482072,16.928876,-1.500000,0.000000,1.000000,4.875000,95.875000
rushing_tds_L8,561.0,0.059661,0.149683,0.000000,0.000000,0.000000,0.011430,1.250000
rushing_fumbles_lost_L8,561.0,0.010759,0.053411,0.000000,0.000000,0.000000,0.002039,1.000000
receptions_L8,561.0,2.175916,1.239121,0.000000,1.166667,2.125000,3.085124,8.750000
receiving_yards_L8,561.0,23.489206,16.717527,-2.000000,11.375000,20.625000,38.856981,105.250000
receiving_tds_L8,561.0,0.139510,0.155707,0.000000,0.000000,0.125000,0.228071,1.000000
receiving_fumbles_lost_L8,561.0,0.012040,0.034028,0.000000,0.000000,0.000000,0.011625,0.500000
targets_L8,561.0,3.243379,1.883695,0.000000,1.875000,3.000000,4.865357,13.000000
carries_L8,561.0,1.978102,3.859173,0.000000,0.000000,0.228167,1.000000,19.500000
receiving_yards_after_catch_L8,561.0,11.064979,6.857007,0.000000,5.750000,12.110995,13.264437,44.375000
receiving_air_yards_L8,561.0,25.785105,25.230465,-9.750000,2.750000,23.048785,51.788530,137.875000
target_share_L8,561.0,0.102163,0.057819,0.000000,0.057599,0.097661,0.150989,0.402313
carry_share_L8,561.0,0.075873,0.148086,0.000000,0.000000,0.008780,0.040750,0.776125
in_10_share_L8,561.0,0.079307,0.085249,0.000000,0.020875,0.066178,0.097200,0.661625
yards_per_carry_L8,561.0,2.906730,2.853746,-12.000000,0.000000,2.357143,5.500000,14.800000
yards_per_reception_L8,561.0,9.936757,4.413002,-2.000000,7.216217,10.365028,12.594950,47.000000
yards_per_target_L8,561.0,6.715531,2.663007,-2.000000,5.590136,7.278637,7.986461,23.500000
wind,561.0,3.040998,3.074102,0.000000,0.000000,3.000000,6.000000,9.000000
div_game,561.0,0.269162,0.443920,0.000000,0.000000,0.000000,1.000000,1.000000
spread_line,561.0,-0.068627,4.805151,-8.500000,-3.000000,-1.500000,3.000000,8.500000
total_line,561.0,45.530303,4.325688,38.500000,41.500000,43.500000,50.500000,51.500000
outdoors,561.0,0.639929,0.480449,0.000000,0.000000,1.000000,1.000000,1.000000
grass,561.0,0.550802,0.497856,0.000000,0.000000,1.000000,1.000000,1.000000
home_team,561.0,0.502674,0.500439,0.000000,0.000000,1.000000,1.000000,1.000000
pred_total,561.0,22.730838,3.200720,16.500000,20.250000,23.250000,25.000000,30.000000
opp_total,561.0,22.799465,3.264341,16.500000,20.250000,23.250000,25.000000,30.000000
qb_comp,561.0,19.352718,4.307239,8.750000,18.000000,19.500000,22.750000,26.500000
qb_att,561.0,29.397282,5.465539,14.875000,27.666667,30.625000,32.875000,39.000000
qb_yds,561.0,213.772950,51.578681,89.875000,178.500000,199.000000,268.875000,282.125000
qb_pass_td,561.0,1.281194,0.479870,0.625000,1.000000,1.250000,1.625000,2.750000
qb_int,561.0,0.584670,0.268992,0.000000,0.500000,0.625000,0.750000,1.125000
qb_comp_pct,561.0,0.653534,0.044838,0.552795,0.620968,0.645669,0.684588,0.753012
qb_yds_per_att,561.0,7.230472,0.872482,5.520913,6.364103,7.317308,7.950530,8.468504
qb_td_pct,561.0,0.043786,0.014557,0.024194,0.030769,0.042017,0.046154,0.082707
qb_int_pct,561.0,0.020313,0.010423,0.000000,0.015267,0.017921,0.025974,0.046154
pos_RB,561.0,0.256684,0.437194,0.000000,0.000000,0.000000,1.000000,1.000000
pos_TE,561.0,0.256684,0.437194,0.000000,0.000000,0.000000,1.000000,1.000000
pos_WR,561.0,0.486631,0.500267,0.000000,0.000000,0.000000,1.000000,1.000000

In [25]:
dk_flex_df.describe().T

,count,mean,std,min,25%,50%,75%,max
salary,370.0,3940.270270,1452.863701,2500.000000,3000.000000,3300.000000,4775.000000,8500.000000
season,370.0,2024.000000,0.000000,2024.000000,2024.000000,2024.000000,2024.000000,2024.000000
week,370.0,7.000000,0.000000,7.000000,7.000000,7.000000,7.000000,7.000000
index,370.0,201.472973,119.028978,0.000000,97.250000,198.500000,305.500000,409.000000
DK_Pts_RB_DvP,370.0,23.714730,3.968250,16.600000,20.550000,23.362500,27.075000,32.237500
DK_Pts_TE_DvP,370.0,11.174966,2.413632,7.950000,9.212500,11.462500,12.500000,17.525000
DK_Pts_WR_DvP,370.0,35.902723,5.909229,29.012500,30.772500,34.993750,39.934375,49.527500
FD_Pts_RB_DvP,370.0,20.777736,3.630985,14.725000,18.362500,20.462500,23.196875,29.175000
FD_Pts_TE_DvP,370.0,8.799628,1.991446,6.187500,6.975000,9.087500,9.750000,14.275000
FD_Pts_WR_DvP,370.0,28.700020,4.520637,22.762500,24.562500,28.325000,31.371875,38.402500
rushing_yards_L8,370.0,9.129580,18.294527,-1.500000,0.000000,0.250000,6.031250,95.875000
rushing_tds_L8,370.0,0.068210,0.172838,0.000000,0.000000,0.000000,0.011430,1.250000
rushing_fumbles_lost_L8,370.0,0.012817,0.063722,0.000000,0.000000,0.000000,0.000397,1.000000
receptions_L8,370.0,2.165775,1.313146,0.000000,1.125000,1.875000,3.085124,8.750000
receiving_yards_L8,370.0,23.330078,17.777739,-2.000000,10.406250,18.812500,38.673986,105.250000
receiving_tds_L8,370.0,0.140116,0.174984,0.000000,0.000000,0.125000,0.228071,1.000000
receiving_fumbles_lost_L8,370.0,0.009015,0.026546,0.000000,0.000000,0.000000,0.011276,0.250000
targets_L8,370.0,3.180335,1.974237,0.000000,1.750000,2.750000,4.718750,13.000000
carries_L8,370.0,2.102396,4.102024,0.000000,0.000000,0.145833,1.181250,19.500000
receiving_yards_after_catch_L8,370.0,11.307725,7.604901,0.000000,5.750000,12.110995,13.618750,44.375000
receiving_air_yards_L8,370.0,24.630613,26.365988,-9.750000,2.375000,17.937500,45.416667,137.875000
target_share_L8,370.0,0.100599,0.060893,0.000000,0.054540,0.086326,0.147453,0.402313
carry_share_L8,370.0,0.081160,0.158118,0.000000,0.000000,0.007500,0.047625,0.776125
in_10_share_L8,370.0,0.083009,0.095011,0.000000,0.017875,0.062500,0.114719,0.661625
yards_per_carry_L8,370.0,2.630342,2.997077,-12.000000,0.000000,2.086663,4.612080,14.800000
yards_per_reception_L8,370.0,9.951877,4.718015,-2.000000,7.216217,10.288889,12.594950,47.000000
yards_per_target_L8,370.0,6.809156,2.853881,-2.000000,5.571429,7.265396,7.986461,23.500000
wind,370.0,3.189189,3.246327,0.000000,0.000000,3.000000,6.000000,9.000000
div_game,370.0,0.302703,0.460050,0.000000,0.000000,0.000000,1.000000,1.000000
spread_line,370.0,0.091892,5.144754,-9.000000,-3.000000,1.500000,3.000000,9.000000
total_line,370.0,46.414561,3.862533,41.000000,43.000000,47.000000,51.000000,52.000000
outdoors,370.0,0.600000,0.490561,0.000000,0.000000,1.000000,1.000000,1.000000
grass,370.0,0.508108,0.500611,0.000000,0.000000,1.000000,1.000000,1.000000
home_team,370.0,0.500000,0.500677,0.000000,0.000000,0.500000,1.000000,1.000000
pred_total,370.0,23.257478,3.178166,16.000000,22.250000,23.750000,25.000000,30.000000
opp_total,370.0,23.157083,3.186543,16.000000,22.000000,23.750000,25.000000,30.000000
qb_comp,370.0,19.570833,4.405464,8.750000,18.000000,20.312500,22.750000,26.500000
qb_att,370.0,29.565653,5.547124,14.875000,27.666667,31.000000,32.875000,39.000000
qb_yds,370.0,217.196622,53.121878,89.875000,178.375000,221.125000,268.875000,282.125000
qb_pass_td,370.0,1.315541,0.474551,0.625000,1.000000,1.250000,1.625000,2.750000
qb_int,370.0,0.597860,0.257509,0.000000,0.500000,0.625000,0.750000,1.125000
qb_comp_pct,370.0,0.656804,0.046413,0.552795,0.627119,0.649902,0.692580,0.753012
qb_yds_per_att,370.0,7.299765,0.900568,5.520913,6.364103,7.645963,7.950530,8.468504
qb_td_pct,370.0,0.044837,0.014628,0.024194,0.036145,0.043290,0.049618,0.082707
qb_int_pct,370.0,0.020816,0.010325,0.000000,0.015385,0.017921,0.026119,0.046154
pos_RB,370.0,0.264865,0.441859,0.000000,0.000000,0.000000,1.000000,1.000000
pos_TE,370.0,0.272973,0.446090,0.000000,0.000000,0.000000,1.000000,1.000000
pos_WR,370.0,0.462162,0.499241,0.000000,0.000000,0.000000,1.000000,1.000000

In [31]:
# dk_flex_df[dk_flex_df['team'].isin(['IND', 'MIA'])][['pred_total', 'opp_total', 'total_line']]

In [26]:
#dk_flex_df[dk_flex_df.isna().any(axis = 1)]

In [32]:
def change_value(df, name, feature, new_value):
    df.loc[df[name] == name, feature] = new_value
    return df

In [33]:
change_def = input('Do you want to change any values in the def dataframes? ')
while change_def == 'y':
    site = input('Which site? ')
    name = input('Which player? ')
    feature = input('Which feature? ')
    new_value = float(input('Enter new value '))
    if site == 'FD':
        fd_def_df = change_value(fd_def_df, name, feature, new_value)
    else:
        dk_def_df = change_value(dk_def_df, name, feature, new_value)
    change_def = ('Do you want to change any other values in the QB dataframes? ')
    
change_qb = input('Do you want to change any values in the QB dataframes? ')
while change_qb == 'y':
    site = input('Which site? ')
    name = input('Which player? ')
    feature = input('Which feature? ')
    new_value = float(input('Enter new value '))
    if site == 'FD':
        fd_qb_df = change_value(fd_qb_df, name, feature, new_value)
    else:
        dk_qb_df = change_value(dk_qb_df, name, feature, new_value)
    change_qb = ('Do you want to change any other values in the QB dataframes? ')

change_flex = input('Do you want to change any values in the FLEX dataframes? ')
while change_flex == 'y':
    site = input('Which site? ')
    name = input('Which player? ')
    feature = input('Which feature? ')
    new_value = float(input('Enter new value '))
    if site == 'FD':
        fd_flex_df = change_value(fd_flex_df, name, feature, new_value)
    else:
        dk_flex_df = change_value(dk_flex_df, name, feature, new_value)
    change_flex = ('Do you want to change any other values in the QB dataframes? ')

fd_def_cols = list(fd_def_df.columns)
dk_def_cols = list(dk_def_df.columns)
fd_qb_cols = list(fd_qb_df.columns)
dk_qb_cols = list(dk_qb_df.columns)
fd_flex_cols = list(fd_flex_df.columns)
dk_flex_cols = list(dk_flex_df.columns)

def_x_cols = ['spread_line',
 'home_team',
 'outdoors',
 'grass',
 'total_line',
 'opp_total',
 'opp_vs_def_L8',
 'opp_vs_def_L8_lin',
 'opp_vs_def_L8_exp']

qb_x_cols = ['FD_Pts_DvP', 'DK_Pts_DvP', 'QB_role', 'completions_L8', 'attempts_L8',
       'passing_yards_L8', 'passing_tds_L8', 'interceptions_L8', 'sacks_L8',
       'passing_air_yards_L8', 'pacr_L8', 'carries_L8', 'rushing_yards_L8',
       'rushing_tds_L8', 'comp_pct', 'yds_per_attempt', 'td_pct', 'sack_pct',
       'int_pct', 'wind', 'div_game', 'spread_line', 'total_line', 'outdoors',
       'grass', 'home_team', 'pred_total', 'opp_total']

flex_x_cols = ['DK_Pts_RB_DvP', 'DK_Pts_TE_DvP', 'DK_Pts_WR_DvP', 'FD_Pts_RB_DvP',
       'FD_Pts_TE_DvP', 'FD_Pts_WR_DvP', 'rushing_yards_L8', 'rushing_tds_L8',
       'rushing_fumbles_lost_L8', 'receptions_L8', 'receiving_yards_L8',
       'receiving_tds_L8', 'receiving_fumbles_lost_L8', 'targets_L8',
       'carries_L8', 'receiving_yards_after_catch_L8',
       'receiving_air_yards_L8', 'target_share_L8', 'carry_share_L8',
       'in_10_share_L8', 'yards_per_carry_L8', 'yards_per_reception_L8',
       'yards_per_target_L8', 'wind', 'div_game', 'spread_line', 'total_line',
       'outdoors', 'grass', 'home_team', 'pred_total', 'opp_total', 'qb_comp',
       'qb_att', 'qb_yds', 'qb_pass_td', 'qb_int', 'qb_comp_pct',
       'qb_yds_per_att', 'qb_td_pct', 'qb_int_pct', 'pos_RB', 'pos_TE',
       'pos_WR']

# List of dataframes
df_list = {
    'fd_def_df': fd_def_df,
    'fd_qb_df': fd_qb_df,
    'fd_flex_df': fd_flex_df,
    'dk_def_df': dk_def_df,
    'dk_qb_df': dk_qb_df,
    'dk_flex_df': dk_flex_df
}

# List to store whether each dataframe has missing values
missing_bool_list = []

# Check for missing values in each dataframe and store in the list
# for df in df_list:
#     missing_values = df.isnull().any().any()  # Check for any missing values
#     missing_bool_list.append(missing_values)

for df_name, df in df_list.items():
    missing_values = df.isnull().any().any()  # Check for any missing values
    missing_bool_list.append((df_name, missing_values))

# Create a dictionary mapping each dataframe to its missing value status
missing_dict = dict(missing_bool_list)

# Iterate over the dictionary to handle dataframes with missing values
# Iterate over the dictionary to handle dataframes with missing values
for df_name, has_missing in missing_dict.items():
    if has_missing:
        print(f"{df_name} has missing values")

        # Specify which columns have missing values
        missing_columns = df_list[df_name].columns[df_list[df_name].isna().any()].tolist()
        print(f"Columns with missing values in {df_name}: {missing_columns}")

        # Display rows with missing values
        display(df_list[df_name][df_list[df_name].isna().any(axis=1)])

        # Allow the user to fill missing values
        fill = input('Do you want to fill a value? ').lower()
        while fill == 'y':
            col = input(f"Which column do you want to fill? Choose from {missing_columns}: ")
            name = input('Which player? ')
            new_value = float(input('Enter new value: '))
    
            # Update the dataframe where the 'name' column matches the input player name
            df_list[df_name].loc[df_list[df_name]['name'] == name, col] = new_value
            fill = input('Do you want to fill another value? (y/n) ').lower()

fd_def_df = fd_def_df.dropna()
fd_qb_df = fd_qb_df.dropna()
fd_flex_df = fd_flex_df.dropna()
dk_def_df = dk_def_df.dropna()
dk_qb_df = dk_qb_df.dropna()
dk_flex_df = dk_flex_df.dropna()

fd_def_df = fd_def_df.set_index(['name', 'team', 'position', 'salary', 'opponent', 'status', 'season', 'week'])
dk_def_df = dk_def_df.set_index(['name', 'team', 'position', 'salary', 'opponent', 'status', 'season', 'week'])
fd_qb_df = fd_qb_df.set_index(['name', 'team', 'position', 'salary', 'opponent', 'status', 'season', 'week'])
dk_qb_df = dk_qb_df.set_index(['name', 'team', 'position', 'salary', 'opponent', 'status', 'season', 'week'])
fd_flex_df = fd_flex_df.set_index(['name', 'team', 'position', 'salary', 'opponent', 'status', 'season', 'week'])
dk_flex_df = dk_flex_df.set_index(['name', 'team', 'position', 'salary', 'opponent', 'status', 'season', 'week'])

fd_flex_df = fd_flex_df[flex_x_cols]
dk_flex_df = dk_flex_df[flex_x_cols]
fd_qb_df = fd_qb_df[qb_x_cols]
dk_qb_df = dk_qb_df[qb_x_cols]
fd_def_df = fd_def_df[def_x_cols]
dk_def_df = dk_def_df[def_x_cols]

all_conditions = all([
    list(fd_def_df.columns) == def_x_cols,
    list(dk_def_df.columns) == def_x_cols,
    list(fd_qb_df.columns) == qb_x_cols,
    list(dk_qb_df.columns) == qb_x_cols,
    list(fd_flex_df.columns) == flex_x_cols,
    list(dk_flex_df.columns) == flex_x_cols
])

if not all_conditions:
    print("Not all column orders match training data.")

change_datasets = input('Did dataset values change? ')
if change_datasets == 'y':
    fd_flex_df.to_csv('FD_FLEX_for_model_' + str(season) + '_' + str(week) + '.csv')
    dk_flex_df.to_csv('DK_FLEX_for_model_' + str(season) + '_' + str(week) + '.csv')
    fd_qb_df.to_csv('FD_qb_for_model_' + str(season) + '_' + str(week) + '.csv')
    dk_qb_df.to_csv('DK_qb_for_model_' + str(season) + '_' + str(week) + '.csv')
    fd_def_df.to_csv('FD_def_for_model_' + str(season) + '_' + str(week) + '.csv')
    dk_def_df.to_csv('DK_def_for_model_' + str(season) + '_' + str(week) + '.csv')

Do you want to change any values in the def dataframes?  n
Do you want to change any values in the QB dataframes?  n
Do you want to change any values in the FLEX dataframes?  n

dk_def_df has missing values
Columns with missing values in dk_def_df: ['total_line', 'opp_total']

,position,salary,team,opponent,week,season,spread_line,home_team,outdoors,grass,total_line,opp_total,opp_vs_def_L8,opp_vs_def_L8_lin,opp_vs_def_L8_exp,name,status
4,D,3200,IND,MIA,7,2024,3.0,1,0,0,NaN,NaN,10.375,10.84,10.100,IND,Active
11,D,2800,MIA,IND,7,2024,-3.0,0,0,0,NaN,NaN,4.375,4.57,4.145,MIA,Active

Do you want to fill a value?  y
Which column do you want to fill? Choose from ['total_line', 'opp_total']:  total_line
Which player?  MIA
Enter new value:  46.4
Do you want to fill another value? (y/n)  y
Which column do you want to fill? Choose from ['total_line', 'opp_total']:  opp_total
Which player?  MIA
Enter new value:  23.2
Do you want to fill another value? (y/n)  y
Which column do you want to fill? Choose from ['total_line', 'opp_total']:  total_line
Which player?  IND
Enter new value:  46.4
Do you want to fill another value? (y/n)  y
Which column do you want to fill? Choose from ['total_line', 'opp_total']:  opp_total
Which player?  IND
Enter new value:  23.2
Do you want to fill another value? (y/n)  n

dk_qb_df has missing values
Columns with missing values in dk_qb_df: ['total_line', 'pred_total', 'opp_total']

,name,team,position,salary,opponent,status,season,week,FD_Pts_DvP,DK_Pts_DvP,...,int_pct,wind,div_game,spread_line,total_line,outdoors,grass,home_team,pred_total,opp_total
11,Tua Tagovailoa,MIA,QB,6100,IND,IR,2024,7,19.2875,20.6625,...,0.030769,0,0,-3.0,NaN,0,0,0,NaN,NaN
12,Anthony Richardson,IND,QB,6000,MIA,Active,2024,7,16.2675,17.1425,...,0.043478,0,0,3.0,NaN,0,0,1,NaN,NaN
13,Joe Flacco,IND,QB,6000,MIA,Active,2024,7,16.2675,17.1425,...,0.031847,0,0,3.0,NaN,0,0,1,NaN,NaN
21,Tyler Huntley,MIA,QB,5100,IND,Active,2024,7,19.2875,20.6625,...,0.016807,0,0,-3.0,NaN,0,0,0,NaN,NaN
33,Skylar Thompson,MIA,QB,4600,IND,Q,2024,7,19.2875,20.6625,...,0.029197,0,0,-3.0,NaN,0,0,0,NaN,NaN
49,Tim Boyle,MIA,QB,4000,IND,Active,2024,7,19.2875,20.6625,...,0.061224,0,0,-3.0,NaN,0,0,0,NaN,NaN
50,Sam Ehlinger,IND,QB,4000,MIA,Active,2024,7,16.2675,17.1425,...,0.029703,0,0,3.0,NaN,0,0,1,NaN,NaN

Do you want to fill a value?  y
Which column do you want to fill? Choose from ['total_line', 'pred_total', 'opp_total']:  total_line
Which player?  Anthony Richardson
Enter new value:  46.4
Do you want to fill another value? (y/n)  y
Which column do you want to fill? Choose from ['total_line', 'pred_total', 'opp_total']:  pred_total
Which player?  Anthony Richardson
Enter new value:  23.2
Do you want to fill another value? (y/n)  y
Which column do you want to fill? Choose from ['total_line', 'pred_total', 'opp_total']:  opp_total
Which player?  Anthony Richardson
Enter new value:  23.2
Do you want to fill another value? (y/n)  y
Which column do you want to fill? Choose from ['total_line', 'pred_total', 'opp_total']:  total_line
Which player?  Joe Flacco
Enter new value:  46.4
Do you want to fill another value? (y/n)  y
Which column do you want to fill? Choose from ['total_line', 'pred_total', 'opp_total']:  pred_total
Which player?  Joe Flacco
Enter new value:  23.2
Do you want to fill another value? (y/n)  y
Which column do you want to fill? Choose from ['total_line', 'pred_total', 'opp_total']:  opp_total
Which player?  Joe Flacco
Enter new value:  23.2
Do you want to fill another value? (y/n)  y
Which column do you want to fill? Choose from ['total_line', 'pred_total', 'opp_total']:  total_line
Which player?  Tyler Huntley
Enter new value:  46.4
Do you want to fill another value? (y/n)  y
Which column do you want to fill? Choose from ['total_line', 'pred_total', 'opp_total']:  pred_total
Which player?  Tyler Huntley
Enter new value:  23.2
Do you want to fill another value? (y/n)  y
Which column do you want to fill? Choose from ['total_line', 'pred_total', 'opp_total']:  opp_total
Which player?  Tyler Huntley
Enter new value:  23.2
Do you want to fill another value? (y/n)  n
Did dataset values change?  y

In [ ]:
# dk_flex_df.loc[dk_flex_df['name'] == 'Sione Vaki', 'pos_RB'] = 1
# dk_flex_df.loc[dk_flex_df['name'] == 'Sione Vaki', 'pos_WR'] = 0
# dk_flex_df.loc[dk_flex_df['name'] == 'Sione Vaki', 'pos_TE'] = 0

# dk_flex_df.loc[dk_flex_df['name'] == 'Zach Wood', 'pos_RB'] = 0
# dk_flex_df.loc[dk_flex_df['name'] == 'Zach Wood', 'pos_WR'] = 0
# dk_flex_df.loc[dk_flex_df['name'] == 'Zach Wood', 'pos_TE'] = 1

# dk_flex_df.loc[dk_flex_df['name'] == 'Evan Deckers', 'pos_RB'] = 0
# dk_flex_df.loc[dk_flex_df['name'] == 'Evan Deckers', 'pos_WR'] = 0
# dk_flex_df.loc[dk_flex_df['name'] == 'Evan Deckers', 'pos_TE'] = 1

# dk_flex_df.loc[dk_flex_df['name'] == 'Malik Cunningham', 'pos_RB'] = 0
# dk_flex_df.loc[dk_flex_df['name'] == 'Malik Cunningham', 'pos_WR'] = 1
# dk_flex_df.loc[dk_flex_df['name'] == 'Malik Cunningham', 'pos_TE'] = 0

In [ ]:
###Checking proper column order

In [ ]:
# fd_qb_df.head()

In [ ]:
# dk_qb_df.head()

In [ ]:
# fd_def_df.head()

In [ ]:
# dk_def_df.head()

In [ ]:
# fd_flex_df.head()

In [ ]:
# dk_flex_df.head()

In [ ]:
# fd_def_df.info()

In [ ]:
# dk_def_df.info()

In [ ]:
# fd_qb_df.info()

In [ ]:
# dk_qb_df.info()

In [ ]:
# fd_flex_df.info()

In [ ]:
# dk_flex_df.info()

In [ ]:


# missing_bool_list = []
# df_list = [fd_def_df, fd_qb_df, fd_flex_df, dk_def_df, dk_qb_df, dk_flex_df]

# for df in df_list:
#     missing_values = df.isnull().any().any()
#     missing_bool_list.append(missing_values)

# missing_dict = dict(list(zip(df_list, missing_bool_list)))

# for k, v in missing_dict.items():
#     if v == True:
#         print(f"{k} has missing values")
#         df[df.isna().any(axis = 1)]
#         col = input('Which column do you want to fill? ')
#         name = input('Which player? ')
#         new_value = float(input('Enter new value: '))
#         df.loc[df['name'] == name, col] = new_value

In [ ]:
# dk_flex_df[dk_flex_df.isna().any(axis = 1)]

In [ ]:
# dk_flex_df.info()

In [ ]:
# fd_flex_df.head()

In [ ]:
# dk_flex_df.head()

In [ ]:
# fd_def_df.head()

In [ ]:
# dk_def_df.head()

In [ ]:
fd_flex_df.head()

In [ ]:
fd_flex_df[fd_flex_df['team'] == 'WAS']